### ISSUE TITLE
可否增加，自行调整关服通知内容的功能呢？

### ISSUE THREAD

**Issue by yanruodi1412** [Cassianvale/palworld-python-script#1]
首先感谢大佬脚本。用上以后游玩的体验好太多了实在。辛苦大佬维护了，注意身体少熬夜hhhhhh

其次想请问下，可否新增个功能，通过.ini的配置文件调整下关服通知内容呢？

再次感谢大佬的贡献。

**Comment by Cassianvale** [comment]
可以，但是我测试下来服务器RCON消息会忽略空格后的内容，而且无法输入中文就很奇怪，加的话当然可以加

**Comment by yanruodi1412** [comment]
> 可以，但是我测试下来服务器RCON消息会忽略空格后的内容，而且无法输入中文就很奇怪，加的话当然可以加

感谢。我昨天自己运行rcon的时候也是，多加了空格就自动关掉了。我以为是rcon的问题，后来搜了搜才知道是帕鲁的事儿。
