### ISSUE TITLE
同一目录提示找不到配置

### ISSUE THREAD

**Issue by songsongQAQ** [Cassianvale/palworld-python-script#11]
![微信截图_20240126224644](https://github.com/Cassianvale/palworld-python-script/assets/42957394/11076907-570b-485a-a406-4aa670e8996c)
![image](https://github.com/Cassianvale/palworld-python-script/assets/42957394/ba0ca438-7947-4f68-a767-1de97a0b36f4)

**Comment by Cassianvale** [comment]
这是你自己打包的吗？

**Comment by Cassianvale** [comment]
如果是自己打的包，之前config.ini获取方式有点问题，现在已经回滚了

**Comment by songsongQAQ** [comment]
感谢重新打包可以正常使用了
